### ISSUE TITLE
Set up tavis-cl process to regenerate HTML files.

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#199]
Right now we have our generated HTML files checked into Git, which isn't great because merging any PR into trunk creates conflicts with all other open branches that Git can't automatically resolve.
(Bikeshed includes some hash of the document in the generated HTML.)

I am wondering if we can set up a tavis-cl workflow to re-generate the HTML on a commit so we can avoid this situation.

**Comment by tidoust** [comment]
The [How to Auto-Deploy Bikeshed Specs](https://github.com/rtoy/auto-deploy-spec#how-to-auto-deploy-bikeshed-specs) guide details steps needed to do that. The main thing being that we'll need two branche (e.g. `master` with the source code and `gh-pages` with the generated spec)

**Comment by mfoltzgoogle** [comment]
Thanks @tidoust!  As we discussed, it should be okay to make gh-pages the publication branch (as that's the standard across other specs).  Folks with open pull requests will need to adjust the base branch through the WebUI or the git commandline.

https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request

CC @pthatcherg @takumif

**Comment by mfoltzgoogle** [comment]
And let's call the base branch "master".

**Comment by mfoltzgoogle** [comment]
This seems to be working well for the spec!

One question:  Will checkins to the markdown files (*.md) automatically be merged from the `master` branch to the `gh-pages` branch?

**Comment by mfoltzgoogle** [comment]
Closing as the GitHub workflows have been operating smoothly (after fixing the Pygments issue).
