### ISSUE TITLE
 Determine if there is an advantage to session resumption outside of early data.

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#220]
And if we allow TLS 1.3 session resumption, do we allow early data too?

**Comment by pthatcherg** [comment]
According to Victor, there is no advantage, and big disadvantages.

**Comment by mfoltzgoogle** [comment]
> https://www.w3.org/2019/09/15-webscreens-minutes.html#x05

ACTION: mfoltzgoogle to remove notes about the TLS profile; if you use 1.3, you can get away of specifying profile, because 1.3 gets rid of all the bad choices.

**Comment by mfoltzgoogle** [comment]
Also:

https://www.w3.org/2019/09/15-webscreens-minutes.html#x08

> RESOLVED: Specifically ban 0-RTT data.

**Comment by mfoltzgoogle** [comment]
Addressed by #252.
