### ISSUE TITLE
Migrate to Second Screen WG

### ISSUE THREAD

**Issue by tidoust** [w3c/openscreenprotocol#237]
The [new charter of the Second Screen Working Group](https://www.w3.org/2014/secondscreen/charter-2020.html) includes the Open Screen Protocol. We should transfer the repository to the W3C organization as a result. May I proceed?

To avoid broken links, the easiest option is to proceed as the WICG with a main `webscreens` repo published to `https://webscreens.github.io/` and a script-based redirection in an `openscreenprotocol` folder as done in https://github.com/WICG/wicg.github.io. @anssiko, fine if I do that?

I'll update the README and add a `w3c.json` file after transfer.

**Comment by anssiko** [comment]
Thank you for your help, please migrate using WICG best practices.

**Comment by anssiko** [comment]
Note to us: update also https://www.w3.org/2014/secondscreen/

**Comment by tidoust** [comment]
Repo transferred, files updated, redirection put in place, group home page updated as well. I'm closing this issue accordingly, let me know if you spot anything wrong!

**Comment by anssiko** [comment]
Everything looks great, much thanks!
