### ISSUE TITLE
mv value needs encoding specified

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#239]
The `mv` value in the mDNS TXT record is an integer, but the spec does not say how to encode it.

Choices include:
1. ASCII as hex or base10
1.  Big endian (network byte order)
1.  QUIC varint

Since values are likely to remain small (< 10000), I would favor option 1 which prioritizes readability.

**Comment by chrisn** [comment]
I agree, and this would be consistent as the other values in the TXT record are also readable.

As an aside, reading this part of the OSP spec, there's a reference to RFC5122 for the `fp` field - should this be RFC8122?

**Comment by mfoltzgoogle** [comment]
Addressed by #253.
