### ISSUE TITLE
[question] Are there any receiver application in the wild?

### ISSUE THREAD

**Issue by jimmywarting** [w3c/openscreenprotocol#243]
I'm just looking around to test and maybe see if there is any software application to Mac or Android that uses the open screen protocol.

Specifically I'm looking if i can turn any of my devices to a receiver UA and play things on it from chrome without owning a chromecast. is it possible?

**Comment by rektide** [comment]
TIL there is an ["openscreen"](https://chromium.googlesource.com/openscreen/) project!

(Learned via https://github.com/w3c/media-and-entertainment/issues/22)

**Comment by jimmywarting** [comment]
Thanks @rektide, wish more cast receivers could be more united and start to adapt to this new open screen protocol standard, Got too many different protocols already, chromecast, miracast, airplay, DIAL, amazon fling, samsung cast etc... Everything don't work together if you have different kind of devices or softwares (browser).

And i hope too see more software in the wild in the feature

**Comment by rektide** [comment]
I too am very very very very very excited to see the w3c working to standardized a means for software to define & use remote systems. :) This is such an important development for the technical world, such a key piece of technology to enable us to build interesting things. Good luck all. @jimmywarting, hopefully we see some additional implementations. :)

**Comment by mfoltzgoogle** [comment]
Hello @rektide and @jimmywarting, the Chrome team is developing an open-source implementation of the Open Screen Protocol as part of the Open Screen Library project.

https://chromium.googlesource.com/openscreen/ 

There are instructions on how to build a simple demo here.

https://chromium.googlesource.com/openscreen/+/refs/heads/master/osp/demo/

The caveat is that we haven't been able to make much progress this year on implementation, so it is lagging behind the spec, but you can explore the code to understand more about how the spec can be implemented.

Let me know if you have any more questions.

**Comment by jimmywarting** [comment]
Thanks @mfoltzgoogle for that information.

> Let me know if you have any more questions.

Just a tiny one: Do you know if chrome (or any browser) supports the new openscreen protocol yet - or is everything just to experimental at this stage?
