### ISSUE TITLE
Survey on registries

### ISSUE THREAD

**Issue by tidoust** [w3c/openscreenprotocol#250]
The Second Screen Working Group maintains an [Open Screen Protocol Capabilities Registry](https://github.com/w3c/openscreenprotocol/blob/master/capabilities.md) in a separate Markdown file for now.

W3C has no standard way to maintain registries. The W3C Process Community Group and the Advisory Board are currently drafting a process for registries (see a [list of related issues](https://github.com/w3c/w3process/issues?q=is%3Aissue+is%3Aopen+registries)), and W3C is conducting a survey across groups on the topic.

This survey asks follow up questions to the [TPAC 2020 Process 2021 presentation](https://www.w3.org/2020/10/TPAC/talk/Process2021#talk). Main questions for the group are the following:

## Do we need a Candidate Recommendation phase?

Would your group find value in signalling to the community in a Candidate Recommendation (CR) phase for the Registry Definition to ask “we think we're done, please check, before we ask for a Proposed Recommendation (PR) transition” even though pure registries do not have a “call for implementations”, or should we give registries a process that skips CR? (See [Do we need both CR and PR?](https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-cr-pr))

- [ ] Registries should have a CR phase to experimentally validate the Working Draft before requesting AC approval.
- [x] Registries do not need a CR phase to experimentally validate the Working Draft before requesting AC approval.
- [ ] No opinion

## Separate track?

The normal practice is for registries to be distinct, and different from, the specifications that define, embed, or use them. They are maintained differently, they have different approval status, and therefore are published separately. Does your group think we should define registries as being on the W3C Recommendation Track, or should they have their own separate W3C Registry Track (which clearly detaches them from the W3C Patent Policy)? (See [Separate track?](https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-track))

- [ ] Separate track is better
- [ ] Re-using Recommendation Track as-is is better
- [x] No opinion
 

## Registry definitions and tables

Does your group think your registries benefit from the ability to publish definitions and tables separately? (Not just separate files within the same publication on /TR, but under completely separate /TR shortnames?) (See [Must be together?](https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-must-together) and [May be separate?](https://www.w3.org/2020/10/TPAC/talk/Process2021#reg-td-separate))

- [ ] Yes, we need this
- [ ] We'd use it if it was available but can live without
- [x] We would not use this
- [ ] We think it's harmful

Further comments are welcome as well.

I used checkboxes in the above lists but note choices are mutually exclusive. I selected choices that, I believe, would work for the group, but that's just meant to be a way to kick-off the discussion ;-)

Any feedback?

Deadline for the survey is 10 February 2021.

**Comment by tidoust** [comment]
Quick note that deadline for the survey is tomorrow. Absence of feedback is fine, I'll assume that this means that people in the group don't have particularly strong positions on this (or that the questions are not clear enough), and will simply ignore the survey.

**Comment by anssiko** [comment]
+1 for @tidoust's selections.

**Comment by mfoltzgoogle** [comment]
Sorry for missing this survey - but since the registry we are using is closely tied to a single deliverable, the selections by @tidoust looks good to me.

**Comment by tidoust** [comment]
Closing down this issue. I replied to the survey on behalf of the group.
