### ISSUE TITLE
Rename default branch to "main"

### ISSUE THREAD

**Issue by tidoust** [w3c/openscreenprotocol#274]
We're progressively renaming default branches of W3C repositories from `master` to `main`. I'd like to do that for this repository.

Migration should be mostly transparent, except that [branch names of local clones will have to be updated](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes). The pending PR should not require any update.

@mfoltzgoogle May I go ahead and change the default branch name?

**Comment by plehegar** [comment]
ping

**Comment by mfoltzgoogle** [comment]
@tidoust Please go ahead, and thank you for taking care of htis.
