### ISSUE TITLE
Consider removing support for P-521

### ISSUE THREAD

**Issue by sleevi** [w3c/openscreenprotocol#277]
A number of user agents intentionally decline to implement P-521, due to the significant performance overheads incurred relative to the limited security benefit provided in practice. For example, both Chrome and Firefox prohibit such certificates within TLS connections.

The current language includes P-521 as optional, as captured at https://github.com/w3c/openscreenprotocol/blob/5488c7b7cce9c9c64ba97348a8deb0c6c50eb9bb/index.bs#L363-L371

This will likely exacerbate interoperability issues, and also arguably incompatible with the goal stated in Non-Functional Requirements, namely https://github.com/w3c/openscreenprotocol/blob/5488c7b7cce9c9c64ba97348a8deb0c6c50eb9bb/index.bs#L206-L210

Suggestion: Remove P-521.

**Comment by mfoltzgoogle** [comment]
Closed by #295.
