### ISSUE TITLE
The keyUsage name is digitalSignature, not signing

### ISSUE THREAD

**Issue by sleevi** [w3c/openscreenprotocol#279]
The current certificate profile states:
https://github.com/w3c/openscreenprotocol/blob/5488c7b7cce9c9c64ba97348a8deb0c6c50eb9bb/index.bs#L412-L415

The `Signing` key usage should refer to the precise key usage defined in [RFC 5280, Section 4.2.1.3](https://tools.ietf.org/html/rfc5280#section-4.2.1.3), which is `digitalSignature`

**Comment by mfoltzgoogle** [comment]
Closed by #288.
