### ISSUE TITLE
Clarify `time-scale` field

### ISSUE THREAD

**Issue by chrisn** [w3c/openscreenprotocol#287]
Reading the protocol detail in Appendix A, I noticed that the `time-scale` field in the [`audio-encoding-offer`](https://w3c.github.io/openscreenprotocol/#audio-encoding-offer) message
wasn't clear. What value is expected, and what are the measurement units does it use?

**Comment by mfoltzgoogle** [comment]
The explanation of the time-scale is in the description of how times and durations are represented in remote playback messages:

> All times, time ranges, and durations (such as position, duration, and seekable-time-ranges) used above use a common [media-time](http://localhost:8000/#media-time) value (see Appendix A) which includes a time scale. This allows time values which work on different time scales to be expressed without loss of precision. The scale is represented in hertz, such as 90000 for 90000 Hz, a common time scale for video.

It agree would be better to pull the description further up because it is also used in `audio-encoding-offer`, `video-encoding-offer`, and `data-encoding-offer`.

**Comment by mfoltzgoogle** [comment]
Closed by #298.
