### ISSUE TITLE
Investigate message latency requirements for media sync

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#80]
It would be helpful to have an upper bound for PresentationConnection message latency based on use cases like media synchronization or lip sync.

From https://www.w3.org/2017/11/07-webscreens-minutes.html#x08:

ACTION: @chrisn  to propose latency ranges for media synchronization use cases (lip sync vs frame sync)

**Comment by mfoltzgoogle** [comment]
Also clock synchronization and clock skew correction were mentioned as potential uses for connection messages.  The HbbTV media synchronization spec may provide some inspiration.

**Comment by chrisn** [comment]
A rough model of different use cases vs accuracy requirements is Figure 1 in [this paper](https://dl.acm.org/citation.cfm?doid=2932206.2932214), shown below:

![sync-accuracy-requirements](https://user-images.githubusercontent.com/57790/40237682-6edb8198-5ab1-11e8-9a04-2f5d1fd86dda.png)

**Comment by mfoltzgoogle** [comment]
To close this out I think a note that implementations should strive to send/receive messages within the smallest latency bounds possible, and no greater than the lip sync threshold of 45ms.

**Comment by mfoltzgoogle** [comment]
> Thanks @chrisn. I will file a followup issue for the sub-10ms use case.

Filed https://github.com/w3c/openscreenprotocol/issues/325 for this.
