### ISSUE TITLE
[QUIC] Find out timeline for TLS 1.3 and QUIC v1

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/openscreenprotocol#82]
From https://www.w3.org/2017/11/07-webscreens-minutes.html#x21:
- ACTION: @schien to check the timeline of TLS 1.3 deployments from Mozilla's editors

(Seems a little silly for this, but I'm filing issues for all TPAC action items)

**Comment by schien** [comment]
This Akamai's [blogpost](https://blogs.akamai.com/2017/10/i-can-haz-tls-13.html) has pretty good summary of the current status of TLS 1.3 deployment. The failure rate caused by middlebox is still too high. More information would be available after the IETF 100 held in mid-Nov 2017.

**Comment by chrisn** [comment]
Here's the info I've been given:

At the current time, TLS 1.3 is at the IESG Review stage of the IETF process. There are many TLS implementations that are converging on that final version.

This [blog post](https://blog.cloudflare.com/you-get-tls-1-3-you-get-tls-1-3-everyone-gets-tls-1-3/) from CloudFlare provides more details. According to this, the middlebox issue mentioned by @schien seems to have been mitigated. Also, Chrome enabled TLS 1.3 by default in [version 65](https://www.chromestatus.com/features/5712755738804224) while Firefox did so in [version 60](https://www.mozilla.org/en-US/firefox/60.0/releasenotes/).

**Comment by chrisn** [comment]
Some further information on QUIC: QUIC v1 is intended to be delivered by end of year, wjhere the current focus is on the transport. [This page](https://github.com/quicwg/base-drafts/wiki/Implementations) has details of implementations.

**Comment by tomoyukilabs** [comment]
Updated: TLS 1.3 is now [RFC 8446](https://tools.ietf.org/html/rfc8446).

**Comment by mfoltzgoogle** [comment]
QUIC v1 was published as four standards track RFCs in ~ May 2021: https://www.akamai.com/blog/performance/http3-and-quic-past-present-and-future

1. https://www.rfc-editor.org/rfc/rfc9000.html
2. https://www.rfc-editor.org/rfc/rfc9001.html
3. https://www.rfc-editor.org/rfc/rfc9002.html
4. https://www.rfc-editor.org/rfc/rfc9368

We should update document cross-references where needed, then close this out.

**Comment by mfoltzgoogle** [comment]
Closed by #310.
