### ISSUE TITLE
Disconnect/Reconnect of RemotePlayback API

### ISSUE THREAD

**Issue by igarashi50** [w3c/openscreenprotocol#89]
Presentation API supports the use case of disconnect/reconnect of the presentation session. Open Screen protection needs to support the function.  I wonder that RemotePlaback API could also support the use case of disconnect/reconnect if the underling open screen protocol supports the function.

**Comment by mfoltzgoogle** [comment]
This sounds a lot like w3c/remote-playback#5 and I posted there:

> We've made a change to the OSP to make it compatible with this scenario, but it would be a new feature as far as the Remote Playback API is concerned. I agree with Anssi that this makes sense to defer to v2.

If there is still interest in this scenario, suggest posting there (or bringing it up as an agenda item at TPAC).  Once the API supports this use case, we can adjust OSP if needed.
